<?php

//множественное наследование через трейты/миксины/примеси+интерфейсы
class Dog extends Animal
{
    public function getAge(): int
    {
        return 234; // TODO: Change the autogenerated stub
    }

    public function sayGAV() {
        return 'gav-gav-gav!';
    }
}